config-version: 3

entities:
  auto-spawn-tick: 200
  worlds-spawn-disabled: "exampleworld1,exampleworld2"
  despawn-entities: true
  despawn-ticks: 10000

max-spawns:
  bat: 0
  blaze: 0
  chicken: 1
  cow: 1
  creeper: 0
  enderman: 0
  ghast: 0
  husk: 0
  horse: 0
  mooshroom: 0
  ocelot: 0
  pig: 1
  polarbear: 0
  rabbit: 0
  stray: 0
  sheep: 1
  skeleton: 0
  spider: 0
  witch: 0
  witherskeleton: 0
  wolf: 0
  zombie: 0
